### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'getRootLen')

### ISSUE THREAD

**Issue by pobearm** [r3inbowari/go-mod-explorer#14]
VSCODE :
版本: 1.66.2 (user setup)
提交: dfd34e8260c270da74b5c2d86d61aee4b6d56977
日期: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

mod explorer version:
v0.1.8

go version:
v1.17.9

issue:
nothing displayed in explorer windows.
click hot-key:  ctl+shift+',   show a error message:  Cannot read properties of undefined (reading 'getRootLen')

**Comment by r3inbowari** [comment]
Thanks, but whether we have a detailed reproduction? 

it works on this envs, Is there cause by difference way of installation?
env: 
Version: 1.66.2 (system setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22581

**Comment by pobearm** [comment]
I installed this extention from vscode's ui panel.
I try to delete this extention from .vscode folder, then reinstall it.
Nothing better hanpped.

I guess it may be related to the mod file format of golang 1.17. 
The mod file of 1.17 records direct dependency and indirect dependency separately.



***@***.***
 
From: r3inbowari
Date: 2022-04-20 13:13
To: r3inbowari/go-mod-explorer
CC: Po Bear; Author
Subject: Re: [r3inbowari/go-mod-explorer] Error: Cannot read properties of undefined (reading 'getRootLen') (Issue #14)
Thanks, but whether we have a detailed reproduction?
it works on this envs, Is there cause by difference way of installation?
env:
Version: 1.66.2 (system setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22581

**Comment by r3inbowari** [comment]
![image](https://user-images.githubusercontent.com/30739857/164169674-a355abd1-98a3-405e-9487-5d599f9bb856.png)
Confusingly, I use 1.17 go fotmat(separate mode), but it still works.

**Comment by pobearm** [comment]
[2022-04-21 08:53:58.862] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'getRootLen')
    at c:\Users\pobear\.vscode\extensions\r3inbowari.gomodexplorer-0.1.8\dist\extension.js:1:4511
    at m._executeContributedCommand (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760)
    at m.$executeContributedCommand (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302)
    at i._doInvokeHandler (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) gomod.focus {"value":"r3inbowari.gomodexplorer","_lower":"r3inbowari.gomodexplorer"}

I got this logs, could be help?



***@***.***
 
From: r3inbowari
Date: 2022-04-20 15:07
To: r3inbowari/go-mod-explorer
CC: Po Bear; Author
Subject: Re: [r3inbowari/go-mod-explorer] Error: Cannot read properties of undefined (reading 'getRootLen') (Issue #14)

Confusingly, I use 1.17 go fotmat(separate mode), but it still works.

**Comment by r3inbowari** [comment]
> [2022-04-21 08:53:58.862] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'getRootLen') at c:\Users\pobear\.vscode\extensions\r3inbowari.gomodexplorer-0.1.8\dist\extension.js:1:4511 at m._executeContributedCommand (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760) at m.$executeContributedCommand (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302) at i._doInvokeHandler (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826) at i._invokeHandler (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510) at i._receiveRequest (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171) at i._receiveOneMessage (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841) at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947 at u.invoke (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145) at v.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856) at d.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034) at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275 at u.invoke (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145) at v.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856) at d.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034) at o._receiveMessage (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615) at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149 at u.invoke (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145) at v.fire (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856) at v.acceptChunk (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865) at c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995 at Socket.P (c:\Users\pobear\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797) at Socket.emit (node:events:390:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) gomod.focus {"value":"r3inbowari.gomodexplorer","_lower":"r3inbowari.gomodexplorer"} I got this logs, could be help? ***@***.*** From: r3inbowari Date: 2022-04-20 15:07 To: r3inbowari/go-mod-explorer CC: Po Bear; Author Subject: Re: [r3inbowari/go-mod-explorer] Error: Cannot read properties of undefined (reading 'getRootLen') (Issue #14) Confusingly, I use 1.17 go fotmat(separate mode), but it still works. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Thank you, These are useful!
But another question is why nothing displayed in explorer windows. Could you check whether go exists in your system environments?

**Comment by r3inbowari** [comment]
When there is nothing in the explorer, the shortcut key will not work, because focusing requires at least one item in the explorer.

**Comment by r3inbowari** [comment]
Explorer will be empty if the go command line cannot be run globally.
